name: CopiMineEconomyCore
version: '1.0.0'
main: me.copimine.economycore.CopiMineEconomyCore
api-version: '1.21'
author: CopiMine
load: POSTWORLD
libraries:
  - org.postgresql:postgresql:42.7.5
softdepend:
  - PlaceholderAPI
  - LuckPerms
  - Essentials
