from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SERVER = ROOT / "copimine-end-event"
DOMAIN = SERVER / "src" / "me" / "copimine" / "endevent" / "domain"
EVENT = SERVER / "src" / "me" / "copimine" / "endevent" / "CopiMineEndEvent.java"
GENERATOR = SERVER / "tools" / "GenerateBossAnimationPoses.ps1"
GENERATED = DOMAIN / "GeneratedBossAnimationPoses.java"
POLICY = DOMAIN / "BossAnimationPosePolicy.java"
RUNNER = ROOT / "tests" / "RunEndRiftEventChecks.ps1"
ANIMATION_ROOT = (
    ROOT
    / "CopiMineClient"
    / "src"
    / "main"
    / "resources"
    / "assets"
    / "copimineclient"
    / "models"
    / "entity"
    / "end_rift_guardian"
    / "animations"
)


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def test_generator_is_the_owner_of_checked_in_server_pose_resource() -> None:
    source = read(GENERATOR)
    generated = read(GENERATED)
    assert "CopiMineClient\\src\\main\\resources" in source
    assert "geometry.json" in source
    assert "idle.json" in source and "running.json" in source
    assert "udar_iz_grudi.json" in source
    assert "udar_po_zemle.animation.json" in source
    assert "-Check" in source
    assert "unsupported" in source.lower()
    assert "finite" in source.lower()
    assert "duplicate keyframe" in source.lower()
    assert "unknown geometry bone" in source.lower()
    assert "sourceLoop" in source
    assert "does not match clip specification" in source
    digest = re.search(r'SOURCE_DIGEST = "([0-9a-f]{64})"', generated)
    assert digest, "generated pose resource must record its source digest"
    assert "Generated by copimine-end-event/tools/GenerateBossAnimationPoses.ps1" in generated


def test_generated_pose_table_covers_every_boss_hitbox_role() -> None:
    source = read(POLICY)
    generated = read(GENERATED)
    for role in (
        "HEAD",
        "CHEST",
        "PELVIS",
        "LEFT_UPPER_ARM",
        "LEFT_FOREARM",
        "RIGHT_UPPER_ARM",
        "RIGHT_FOREARM",
        "LEFT_LEG",
        "RIGHT_LEG",
    ):
        assert f"PartId.{role}" in source
    for bone in (
        '"head"',
        '"body"',
        '"left_hand"',
        '"left_hand_low"',
        '"right_hand"',
        '"right_hand_low"',
        '"left_leg"',
        '"right_leg"',
        '"left_leg_low"',
        '"right_leg_low"',
        '"group2"',
        '"group"',
    ):
        assert bone in generated
    assert 'record BoneDefinition(String parent' in generated
    assert 'new BoneDefinition("left_hand"' in generated


def test_authoritative_hitbox_update_uses_authored_clock_not_state_offsets() -> None:
    event = read(EVENT)
    assert "BossAnimationPosePolicy" in event
    assert "bossHitboxAnimationId" in event
    assert "bossHitboxAnimationStartedMillis" in event
    assert "BossAnimationPosePolicy.sampleSegments(bossHitboxAnimationId, elapsedTicks)" in event
    assert "new BossHitboxTransformPolicy.PoseOffset(-1.5D" not in event
    assert "new BossHitboxTransformPolicy.PoseOffset(-3.0D" not in event
    start = event.index("private Map<BossHitboxProfile.PartKey, BossHitboxTransformPolicy.PoseOffset> bossHitboxPoseOffsets()")
    end = event.index("private void renderBossHitboxDebug", start)
    pose_method = event[start:end]
    assert "switch (bossAbilityState)" not in pose_method
    assert "System.currentTimeMillis()" in pose_method


def test_client_source_assets_and_pose_gate_are_registered() -> None:
    expected = {
        "idle.json",
        "running.json",
        "swipe.json",
        "hurt.json",
        "dying.json",
        "udar_iz_grudi.json",
        "udar_po_zemle.animation.json",
    }
    assert {path.name for path in ANIMATION_ROOT.iterdir()} >= expected
    runner = read(RUNNER)
    assert "GenerateBossAnimationPoses.ps1" in runner
    assert "-Check" in runner
    assert "BossAnimationPosePolicyTest" in runner
    assert "test_end_event_boss_animation_pose_contract.py" in runner
