. "$PSScriptRoot\ElectionPhase1Validator.Helpers.ps1"
$errors = New-ErrorList
$admin = Read-Utf8 $Paths.Admin

Require-Contains $admin 'private CopiMineEconomyCore economyCore()' 'AdminPlus must resolve EconomyCore through a bridge method.'
Require-Contains $admin 'economy.openAdminEconomyHub(p)' 'AdminPlus economy routes must delegate to EconomyCore.'
Require-Contains $admin 'if(a.equals("open:bank-atms")||a.equals("bank-atm:create-target")||a.startsWith("bank-atm:delete:")||a.startsWith("open:bank-atm:"))' 'AdminPlus must trap legacy ATM admin actions explicitly.'
Require-Contains $admin 'if(a.startsWith("bank:")||a.startsWith("bankpin:"))' 'AdminPlus must trap legacy ATM player actions explicitly.'

Require-NotContains $admin 'openEconomy(p);' 'AdminPlus must not open a local legacy economy hub from active actions.'
Require-NotContains $admin 'economy.openAtmDirectory(p)' 'AdminPlus must not proxy a local ATM directory flow.'
Require-NotContains $admin 'economy.atmService().openAtm' 'AdminPlus must not proxy live ATM click handling.'
Require-NotContains $admin 'economyCore().isAtmBlock' 'AdminPlus must not inspect ATM blocks directly in active runtime.'
Require-NotContains $admin 'private void openEconomy(Player p)' 'AdminPlus must not keep a local economy root implementation.'
Require-NotContains $admin 'private void openBankAtms(Player p)' 'AdminPlus must not keep a live local ATM registry GUI entrypoint.'
Require-NotContains $admin 'private boolean isBankAtmBlock(Block b)' 'AdminPlus must not own ATM block detection.'
Require-NotContains $admin 'private String createBankAtmFromTarget(Player p)' 'AdminPlus must not own ATM creation flow.'
Require-NotContains $admin 'private String archiveBankAtm(Player p,String id)' 'AdminPlus must not own ATM archive flow.'

Require-Contains $admin 'private void openBankAtm(Player p,String atmId)' 'AdminPlus may keep a compatibility ATM wrapper only for redirect safety.'
Require-Contains $admin 'private void legacyOpenBankAtm(Player p,String atmId)' 'If the old ATM GUI remains in source, it must be isolated behind a legacy name.'
Require-Contains $admin 'private boolean handleProtectedVisualInteract(Player p,Entity target,PlayerInteractEntityEvent e)' 'AdminPlus may keep a protected-visual compatibility hook only as a no-op.'
Require-Contains $admin 'private boolean legacyHandleProtectedVisualInteractDisabled(Player p,Entity target,PlayerInteractEntityEvent e)' 'If the old protected-visual ATM path remains in source, it must be isolated behind a disabled legacy name.'
Require-Contains $admin 'private void legacyOpenArTopDisabled(Player p)' 'If the old AR top GUI remains in source, it must be isolated behind a disabled legacy name.'
Require-Contains $admin 'private void legacyOpenArCustodyDisabled(Player p)' 'If the old AR custody GUI remains in source, it must be isolated behind a disabled legacy name.'
Require-Contains $admin 'private void legacyOpenEconomyHealthDisabled(Player p)' 'If the old economy health GUI remains in source, it must be isolated behind a disabled legacy name.'
Require-Contains $admin 'private void legacyOpenBankTransferTargetsDisabled(Player p,String atmId)' 'Legacy ATM transfer target GUI must be isolated behind a disabled legacy name.'
Require-Contains $admin 'private void legacyOpenBankTransferAmountsDisabled(Player p,String atmId,String targetUuid)' 'Legacy ATM transfer amount GUI must be isolated behind a disabled legacy name.'
Require-Contains $admin 'private String legacyDepositArFromHandDisabled(Player p,String atmId)' 'Legacy ATM hand deposit flow must be isolated behind a disabled legacy name.'
Require-Contains $admin 'private String legacyDepositAllArDisabled(Player p,String atmId)' 'Legacy ATM bulk deposit flow must be isolated behind a disabled legacy name.'
Require-Contains $admin 'private long legacyCommitBankDepositDisabled(Player p,String atmId,int amount)' 'Legacy ATM deposit transaction helper must be isolated behind a disabled legacy name.'
Require-Contains $admin 'private void legacyOpenAtmPinPadDisabled(Player p,String atmId,String action,int amount,String pin)' 'Legacy ATM PIN pad helper must be isolated behind a disabled legacy name.'
Require-Contains $admin 'private void legacyHandleAtmPinActionDisabled(Player p,String action)' 'Legacy ATM PIN action flow must be isolated behind a disabled legacy name.'
Require-Contains $admin 'private String legacyTransferBankArDisabled(Player p,String atmId,String targetUuid,String targetName,int amount,String pin)' 'Legacy ATM transfer execution must be isolated behind a disabled legacy name.'
Require-Contains $admin 'private String legacyWithdrawBankArDisabled(Player p,String atmId,int amount,String pin)' 'Legacy ATM withdraw execution must be isolated behind a disabled legacy name.'

Require-NotContains $admin 'private void openArTop(Player p)' 'AdminPlus must not expose a live local AR top GUI entrypoint.'
Require-NotContains $admin 'private void openArCustody(Player p)' 'AdminPlus must not expose a live local AR custody GUI entrypoint.'
Require-NotContains $admin 'private void openEconomyHealth(Player p)' 'AdminPlus must not expose a live local economy health GUI entrypoint.'
Require-NotContains $admin 'private void openBankTransferTargets(Player p,String atmId)' 'AdminPlus must not expose a live local ATM transfer target GUI entrypoint.'
Require-NotContains $admin 'private void openBankTransferAmounts(Player p,String atmId,String targetUuid)' 'AdminPlus must not expose a live local ATM transfer amount GUI entrypoint.'
Require-NotContains $admin 'private String depositArFromHand(Player p,String atmId)' 'AdminPlus must not expose a live local ATM hand deposit flow.'
Require-NotContains $admin 'private String depositAllAr(Player p,String atmId)' 'AdminPlus must not expose a live local ATM bulk deposit flow.'
Require-NotContains $admin 'private long commitBankDeposit(Player p,String atmId,int amount)' 'AdminPlus must not expose a live local ATM deposit transaction helper.'
Require-NotContains $admin 'private void openAtmPinPad(Player p,String atmId,String action,int amount,String pin)' 'AdminPlus must not expose a live local ATM PIN pad helper.'
Require-NotContains $admin 'private void handleAtmPinAction(Player p,String action)' 'AdminPlus must not expose a live local ATM PIN action handler.'
Require-NotContains $admin 'private String transferBankAr(Player p,String atmId,String targetUuid,String targetName,int amount,String pin)' 'AdminPlus must not expose a live local ATM transfer executor.'
Require-NotContains $admin 'private String withdrawBankAr(Player p,String atmId,int amount,String pin)' 'AdminPlus must not expose a live local ATM withdraw executor.'
Require-NotContains $admin 'private int syncArOnline(String actor)' 'AdminPlus must not own AR balance synchronization.'
Require-NotContains $admin 'private void syncAr(Player p)' 'AdminPlus must not own direct AR sync logic.'

Throw-IfErrors 'ValidateCopiMineAdminPlusNoEconomyOwnership'
