. "$PSScriptRoot\ElectionPhase1Validator.Helpers.ps1"
$errors = New-ErrorList
$bundle = Read-FrontendBundle
$index = Read-Utf8 $Paths.FrontendIndex
$combined = $bundle + "`n" + $index

$banned = @(
  'lorem ipsum',
  'generated by',
  'chatgpt',
  'placeholder text',
  'placeholder ui',
  'TODO player-facing',
  'fake dashboard',
  'fake status',
  'demo data'
)

foreach ($needle in $banned) {
  if ($combined.ToLowerInvariant().Contains($needle.ToLowerInvariant())) {
    $errors.Add("Frontend must not ship AI/placeholder text: $needle")
  }
}

Throw-IfErrors 'ValidateCopiMineNoAiPlaceholderText'
