name: CopiMineArtifacts
version: '1.1.0-shops-blocks-prices'
main: me.copimine.artifacts.CopiMineArtifacts
api-version: '1.21'
author: CopiMine
load: POSTWORLD
libraries:
  - org.postgresql:postgresql:42.7.5
depend:
  - CopiMineEconomyCore
softdepend:
  - CopiMineElectionCore
  - CopiMineUltimateAdminPlus
commands:
  cmartifacts:
    description: Открыть лавку артефактов
    usage: /cmartifacts
    aliases: [cartifacts, artifactshop]
  setprice:
    description: Изменить цену предмета
    usage: /setprice <item_id> <price> or /setprice <item_id> <ar|donation> <price>
permissions:
  copimine.artifacts.admin:
    description: Управление лавками артефактов
    default: op
    children:
      copimine.artifacts.shop.create: true
      copimine.artifacts.shop.remove: true
      copimine.artifacts.shop.list: true
      copimine.artifacts.reload: true
      copimine.artifacts.price.set: true
      copimine.artifacts.admin.give: true
  copimine.artifacts.shop.create:
    description: Создание лавок артефактов
    default: op
  copimine.artifacts.shop.remove:
    description: Удаление лавок артефактов
    default: op
  copimine.artifacts.shop.list:
    description: Просмотр лавок артефактов
    default: op
  copimine.artifacts.reload:
    description: Перезагрузка лавки артефактов
    default: op
  copimine.artifacts.price.set:
    description: Изменение цен предметов
    default: op
  copimine.artifacts.admin.give:
    description: Выдача особых артефактов игроку
    default: op
  copimine.artifacts.use:
    description: Использование лавок артефактов
    default: true
