name: CopiMineWorldCore
version: '1.0.0'
main: me.copimine.worldcore.CopiMineWorldCore
api-version: '1.21'
author: CopiMine
load: POSTWORLD
commands:
  cmworld:
    description: Управление доступом к мирам и границами
    usage: /cmworld
permissions:
  copimine.world.admin:
    description: Управление ограничениями и доступом к мирам
    default: op
