name: CopiMineElectionCore
version: '9.2.0-postgres-v4-balance-credit'
main: me.copimine.electioncore.CopiMineElectionCore
api-version: '1.21'
author: CopiMine
load: POSTWORLD
libraries:
  - org.postgresql:postgresql:42.7.5
depend:
  - CopiMineEconomyCore
softdepend:
  - PlaceholderAPI
  - LuckPerms
  - Essentials
commands:
  hidelive:
    description: Скрыть или вернуть панель выборов
    usage: /hidelive
  presidentsay:
    description: Объявление президента
    usage: /presidentsay <chat|title|actionbar> <message>
permissions:
  copimine.election.admin:
    description: Полное управление выборами
    default: op
  copimine.election.cik:
    description: Действия председателя ЦИК
    default: false
  copimine.election.president:
    description: Действия президента
    default: false
  copimine.election.broadcast:
    description: Объявления президента
    default: false
  copimine.election.debug:
    description: Просмотр служебного состояния выборов
    default: op
